<!-- Mon May 26 16:39:57 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadArc" id="000000002bf9c928" desc="IAcadArc: AutoCAD Arc Interface" Application="IAcadApplication 000000013fa12308" ArcLength="7.86301" Area="8.26009" Center="(4.63487 12.1317 0.0)" Document="IAcadDocument 000000002e605618" EndAngle="3.38637" EndPoint="(0.69158 11.1467 0.0)" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e711468" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="44" ObjectID32="44" ObjectName="AcDbArc" OwnerID="45" OwnerID32="45" PlotStyleName="ByLayer" Radius="4.06445" StartAngle="1.45179" StartPoint="(5.11743 16.1674 0.0)" Thickness="0.0" TotalAngle="1.93458" TrueColor="IAcadAcCmColor 000000002e711640" Visible="-1" />
<DwgEntity type="IAcadArc" id="000000002bf9d1e8" desc="IAcadArc: AutoCAD Arc Interface" Application="IAcadApplication 000000013fa12308" ArcLength="10.015" Area="14.8993" Center="(-5.38459 9.91024 0.0)" Document="IAcadDocument 000000002e605618" EndAngle="3.40062" EndPoint="(-9.49174 8.82192 0.0)" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e7116a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="46" ObjectID32="46" ObjectName="AcDbArc" OwnerID="45" OwnerID32="45" PlotStyleName="ByLayer" Radius="4.24889" StartAngle="1.04353" StartPoint="(-3.24668 13.5821 0.0)" Thickness="0.0" TotalAngle="2.35709" TrueColor="IAcadAcCmColor 000000002e711b20" Visible="-1" />
<DwgEntity type="IAcadArc" id="000000002bf9ce68" desc="IAcadArc: AutoCAD Arc Interface" Application="IAcadApplication 000000013fa12308" ArcLength="48.096" Area="215.424" Center="(-18.1933 6.68652 0.0)" Document="IAcadDocument 000000002e605618" EndAngle="1.51876" EndPoint="(-17.762 14.9684 0.0)" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e711a08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="47" ObjectID32="47" ObjectName="AcDbArc" OwnerID="45" OwnerID32="45" PlotStyleName="ByLayer" Radius="8.2931" StartAngle="2.00242" StartPoint="(-21.6627 14.219 0.0)" Thickness="0.0" TotalAngle="5.79952" TrueColor="IAcadAcCmColor 000000002e711dc0" Visible="-1" />
</DwgData>