<!-- Mon May 26 16:40:16 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadXline" id="000000002bd5e518" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.817977 0.575251 0.0)" Document="IAcadDocument 000000002ec72d98" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efac738" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="52" ObjectID32="52" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(33.866 49.0251 0.0)" TrueColor="IAcadAcCmColor 000000002efac670" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002bd5e5c8" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.805537 -0.592545 0.0)" Document="IAcadDocument 000000002ec72d98" EntityTransparency="ByLayer" Handle="1BC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efaca98" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="54" ObjectID32="54" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(33.8784 47.8573 0.0)" TrueColor="IAcadAcCmColor 000000002efac790" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002bd5e888" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.018621 -0.999827 0.0)" Document="IAcadDocument 000000002ec72d98" EntityTransparency="ByLayer" Handle="1BB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efacc18" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="55" ObjectID32="55" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(34.6653 47.45 0.0)" TrueColor="IAcadAcCmColor 000000002efacc70" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002bd5eb48" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(0.998718 0.050628 0.0)" Document="IAcadDocument 000000002ec72d98" EntityTransparency="ByLayer" Handle="1BA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efacfd8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="56" ObjectID32="56" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(35.6827 48.5004 0.0)" TrueColor="IAcadAcCmColor 000000002efacd30" Visible="-1" />
</DwgData>