<!-- Mon May 26 16:40:37 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadHelix" id="000000002bd60828" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013fa12308" BaseRadius="1.36885" Constrain="1" Document="IAcadDocument 000000002f2b2df8" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 00000000363ee2a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="72" ObjectID32="72" ObjectName="AcDbHelix" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" Position="(2.25405 13.3778 0.0)" TopRadius="6.82783" TotalLength="77.4916" TrueColor="IAcadAcCmColor 00000000363ee5a0" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.38962" Twist="0" Visible="-1" />
<DwgEntity type="IAcadHelix" id="000000002bd608d8" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013fa12308" BaseRadius="1.42682" Constrain="1" Document="IAcadDocument 000000002f2b2df8" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 00000000363ee848" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="74" ObjectID32="74" ObjectName="AcDbHelix" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" Position="(34.5102 15.476 0.0)" TopRadius="9.28195" TotalLength="101.322" TrueColor="IAcadAcCmColor 00000000363ee9c0" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.44417" Twist="0" Visible="-1" />
<DwgEntity type="IAcadHelix" id="000000002bd611c8" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013fa12308" BaseRadius="5.23833" Constrain="1" Document="IAcadDocument 000000002f2b2df8" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 00000000363eeb48" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="75" ObjectID32="75" ObjectName="AcDbHelix" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" Position="(19.3948 11.0174 0.0)" TopRadius="0.42723" TotalLength="53.7246" TrueColor="IAcadAcCmColor 00000000363eefc0" TurnHeight="0.333333" Turns="3.0" TurnSlope="-1.36586" Twist="0" Visible="-1" />
</DwgData>