<!-- Mon May 26 16:41:06 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLine" id="000000002bc40168" desc="IAcadLine: AutoCAD Line Interface" Angle="3.04252" Application="IAcadApplication 000000013fa12308" Delta="(-22.6168 2.24807 0.0)" Document="IAcadDocument 000000002b6e87c8" EndPoint="(9.75549 10.0432 0.0)" EntityTransparency="ByLayer" Handle="1CC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e364db8" Layer="0" Length="22.7283" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="42" ObjectID32="42" ObjectName="AcDbLine" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" StartPoint="(32.3723 7.79514 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e364e70" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000002bc40228" desc="IAcadLine: AutoCAD Line Interface" Angle="5.89039" Application="IAcadApplication 000000013fa12308" Delta="(21.3416 -8.8424 0.0)" Document="IAcadDocument 000000002b6e87c8" EndPoint="(32.3723 7.79514 0.0)" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e365178" Layer="0" Length="23.1009" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="44" ObjectID32="44" ObjectName="AcDbLine" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" StartPoint="(11.0307 16.6375 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e365230" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000002bc402e8" desc="IAcadLine: AutoCAD Line Interface" Angle="2.22385" Application="IAcadApplication 000000013fa12308" Delta="(-10.577 13.8256 0.0)" Document="IAcadDocument 000000002b6e87c8" EndPoint="(11.0307 16.6375 0.0)" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e3655f8" Layer="0" Length="17.4075" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="45" ObjectID32="45" ObjectName="AcDbLine" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" StartPoint="(21.6078 2.81192 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e365530" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000002bc403a8" desc="IAcadLine: AutoCAD Line Interface" Angle="4.17869" Application="IAcadApplication 000000013fa12308" Delta="(-6.37622 -10.7907 0.0)" Document="IAcadDocument 000000002b6e87c8" EndPoint="(21.6078 2.81192 0.0)" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e365838" Layer="0" Length="12.5338" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="46" ObjectID32="46" ObjectName="AcDbLine" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" StartPoint="(27.984 13.6027 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e365890" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000002bc40468" desc="IAcadLine: AutoCAD Line Interface" Angle="0.192841" Application="IAcadApplication 000000013fa12308" Delta="(18.2285 3.55944 0.0)" Document="IAcadDocument 000000002b6e87c8" EndPoint="(27.984 13.6027 0.0)" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e365a18" Layer="0" Length="18.5728" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="47" ObjectID32="47" ObjectName="AcDbLine" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" StartPoint="(9.75549 10.0432 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e365ad0" Visible="-1" />
</DwgData>