<!-- Mon May 26 16:41:14 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadMLine" id="000000002b6bff88" desc="IAcadMLine: IAcadMLine Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(9.15538 14.989 0.0 18.7947 10.0057 0.0 ... )" Document="IAcadDocument 000000002b8af448" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002bc47ac8" Justification="0" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" MLineScale="1.0" ObjectID="48" ObjectID32="48" ObjectName="AcDbMline" OwnerID="49" OwnerID32="49" PlotStyleName="ByLayer" StyleName="STANDARD" TrueColor="IAcadAcCmColor 000000002bc47e20" Visible="-1" />
</DwgData>