<!-- Mon May 26 16:41:20 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadPoint" id="000000002e7e9d38" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(16.5251 10.5127 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e893de8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="50" ObjectID32="50" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e893fc0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9df8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(17.6111 9.23422 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894148" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="52" ObjectID32="52" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e894200" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9eb8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(15.8658 5.35995 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894388" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="53" ObjectID32="53" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e8945c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9f78" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(16.0985 6.05732 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894508" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="54" ObjectID32="54" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e894440" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7ea038" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.2401 8.18816 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894988" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="55" ObjectID32="55" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e8948c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7ea0f8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.1018 10.9776 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894c88" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="56" ObjectID32="56" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e893fc0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9d38" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.606 11.2488 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894148" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="57" ObjectID32="57" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e894980" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9df8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e894e08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="58" ObjectID32="58" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e894c20" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9eb8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e8950a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="59" ObjectID32="59" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e895160" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9f78" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.3564 10.5515 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e895348" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="60" ObjectID32="60" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e895280" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7ea038" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(18.891 11.7525 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e8954c8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="61" ObjectID32="61" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e895580" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7ea1b8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(27.928 8.65308 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e895768" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="62" ObjectID32="62" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e895820" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7ea278" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.6279 7.25834 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e895a08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="63" ObjectID32="63" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e895b20" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9d38" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(23.4289 11.9849 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e895168" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="64" ObjectID32="64" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e894c20" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000002e7e9df8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(13.4999 11.4813 0.0)" Document="IAcadDocument 000000002e649a78" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002e8958e8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="65" ObjectID32="65" ObjectName="AcDbPoint" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002e893d80" Visible="-1" />
</DwgData>