<!-- Mon May 26 16:41:29 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000002ebc7628" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="22.2834" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(5.92976 11.9915 6.24287 12.1103 6.53863 12.2675 ... )" Document="IAcadDocument 000000002e793798" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002eace1b8" Layer="0" Length="16.7449" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="66" ObjectID32="66" ObjectName="AcDbPolyline" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002eace390" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002ebc76e8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="121.668" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(28.9217 8.88171 30.6459 5.29844 34.1471 3.41302 ... )" Document="IAcadDocument 000000002e793798" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002eace278" Layer="0" Length="39.7655" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="68" ObjectID32="68" ObjectName="AcDbPolyline" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002eace5d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002ebc7868" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="106.492" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.1081 10.4179 16.1916 14.1675 10.4882 8.74827 ... )" Document="IAcadDocument 000000002e793798" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002eace6f8" Layer="0" Length="39.3372" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="69" ObjectID32="69" ObjectName="AcDbPolyline" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002eace9f0" Visible="-1" />
</DwgData>