<!-- Mon May 26 16:41:42 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadRay" id="000000002b6c3058" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 -1.0 0.0)" Document="IAcadDocument 000000002ed48728" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efcfcf8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="72" ObjectID32="72" ObjectName="AcDbRay" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" SecondPoint="(10.0931 9.19308 0.0)" TrueColor="IAcadAcCmColor 000000002efcfa50" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000002b6c3108" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 1.0 0.0)" Document="IAcadDocument 000000002ed48728" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efcfff8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="74" ObjectID32="74" ObjectName="AcDbRay" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" SecondPoint="(10.0931 11.1931 0.0)" TrueColor="IAcadAcCmColor 000000002efd0050" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000002b6c33c8" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.983378 -0.181571 0.0)" Document="IAcadDocument 000000002ed48728" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efd02f8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="75" ObjectID32="75" ObjectName="AcDbRay" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" SecondPoint="(11.0764 10.0115 0.0)" TrueColor="IAcadAcCmColor 000000002efd01d0" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000002b6c3688" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.98609 0.166213 0.0)" Document="IAcadDocument 000000002ed48728" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002efd04d8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="76" ObjectID32="76" ObjectName="AcDbRay" OwnerID="73" OwnerID32="73" PlotStyleName="ByLayer" SecondPoint="(11.0791 10.3593 0.0)" TrueColor="IAcadAcCmColor 000000002efd0590" Visible="-1" />
</DwgData>