<!-- Mon May 26 16:41:47 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="0000000035f3ede8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="30.5304" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )" Document="IAcadDocument 000000002f18d6d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2544b8" Layer="0" Length="26.5489" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="77" ObjectID32="77" ObjectName="AcDbPolyline" OwnerID="78" OwnerID32="78" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2548d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000035f3eea8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="25.9786" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )" Document="IAcadDocument 000000002f18d6d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f254998" Layer="0" Length="23.4733" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="79" ObjectID32="79" ObjectName="AcDbPolyline" OwnerID="78" OwnerID32="78" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f254d50" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000035f3f028" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="39.634" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )" Document="IAcadDocument 000000002f18d6d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f254b18" Layer="0" Length="26.6957" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="80" ObjectID32="80" ObjectName="AcDbPolyline" OwnerID="78" OwnerID32="78" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f254ff0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000035f3f1a8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="44.2182" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )" Document="IAcadDocument 000000002f18d6d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f254f38" Layer="0" Length="27.1381" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="81" ObjectID32="81" ObjectName="AcDbPolyline" OwnerID="78" OwnerID32="78" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2552f0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000035f3f268" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="299.943" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )" Document="IAcadDocument 000000002f18d6d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f255358" Layer="0" Length="78.293" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="82" ObjectID32="82" ObjectName="AcDbPolyline" OwnerID="78" OwnerID32="78" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f255650" Visible="-1" />
</DwgData>