<!-- Mon May 26 16:41:54 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadSpline" id="00000000360b6708" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013fa12308" Area="45.4007" Closed="0" Closed2="0" ControlPoints="(4.09191 14.0523 0.0 7.35503 5.05999 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 000000002bc2cf98" EndTangent="AutoCAD.Application: General modeling failure" EntityTransparency="ByLayer" FitPoints="nil" FitTolerance="0.0" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003605be78" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="15" Knots="(0.0 0.0 0.0 0.0 1.0 2.0 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="0" ObjectID="83" ObjectID32="83" ObjectName="AcDbSpline" OwnerID="84" OwnerID32="84" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="1" StartTangent="AutoCAD.Application: General modeling failure" TrueColor="IAcadAcCmColor 000000003605be10" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
<DwgEntity type="IAcadSpline" id="00000000360b6c48" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013fa12308" Area="20.1091" Closed="0" Closed2="0" ControlPoints="(28.059 8.80677 0.0 33.9643 7.72128 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 000000002bc2cf98" EndTangent="(0.0 0.0 0.0)" EntityTransparency="ByLayer" FitPoints="(28.059 8.80677 0.0 40.0613 6.22149 0.0 ... )" FitTolerance="1.0e-010" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003605bf98" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="0" Knots="(0.0 0.0 0.0 0.0 12.2776 26.0835 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="3" ObjectID="85" ObjectID32="85" ObjectName="AcDbSpline" OwnerID="84" OwnerID32="84" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="0" StartTangent="(0.0 0.0 0.0)" TrueColor="IAcadAcCmColor 000000003605c230" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
<DwgEntity type="IAcadSpline" id="00000000360b6d28" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013fa12308" Area="46.2417" Closed="0" Closed2="0" ControlPoints="(10.018 7.4954 0.0 15.3906 6.25317 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 000000002bc2cf98" EndTangent="(0.0 0.0 0.0)" EntityTransparency="ByLayer" FitPoints="(10.018 7.4954 0.0 21.1577 6.37137 0.0 ... )" FitTolerance="1.0e-010" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003605c418" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="0" Knots="(0.0 0.0 0.0 0.0 11.1962 20.7142 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="3" ObjectID="86" ObjectID32="86" ObjectName="AcDbSpline" OwnerID="84" OwnerID32="84" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="0" StartTangent="(0.0 0.0 0.0)" TrueColor="IAcadAcCmColor 000000003605c350" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
</DwgData>