<!-- Mon May 26 16:42:00 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadTable" id="00000000360b6c48" desc="IAcadTable: IAcadTable Interface" AllowManualHeights="0" AllowManualPositions="0" Application="IAcadApplication 000000013fa12308" BreaksEnabled="0" BreakSpacing="0.99" Columns="3" ColumnWidth="...Indexed contents not shown..." Direction="(1.0 0.0 0.0)" Document="IAcadDocument 000000002bc2d428" EnableBreak="...Indexed contents not shown..." EntityTransparency="ByLayer" FlowDirection="0" Handle="1BE" HasExtensionDictionary="0" HasSubSelection="0" HeaderSuppressed="0" Height="1.46625" HorzCellMargin="0.06" Hyperlinks="IAcadHyperlinks 000000003631ece8" InsertionPoint="(13.8101 11.2876 0.0)" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" MinimumTableHeight="1.46625" MinimumTableWidth="1.11" ObjectID="87" ObjectID32="87" ObjectName="AcDbTable" OwnerID="88" OwnerID32="88" PlotStyleName="ByLayer" RegenerateTableSuppressed="0" RepeatBottomLabels="0" RepeatTopLabels="0" RowHeight="...Indexed contents not shown..." Rows="3" StyleName="Standard" TableBreakFlowDirection="1" TableBreakHeight="0.0" TableStyleOverrides="nil" TitleSuppressed="0" TrueColor="IAcadAcCmColor 000000003631f1c0" VertCellMargin="0.06" Visible="-1" Width="7.5" />
</DwgData>