[ AutoCAD - Mon May 26 16:45:36 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcad3DPolyline 000000002b9d2ad8>
; IAcad3DPolyline: AutoCAD 3dPolyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Closed = 0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (21.4409 14.6498 0.0 20.8962 5.65378 0.0 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002b9fa338>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002bbc1838>
;   Layer = "0"
;   Length (RO) = 38.6446
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   ObjectID (RO) = 42
;   ObjectID32 (RO) = 42
;   ObjectName (RO) = "AcDb3dPolyline"
;   OwnerID (RO) = 43
;   OwnerID32 (RO) = 43
;   PlotStyleName = "ByLayer"
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002bbc1b30>
;   Type = 0
;   Visible = -1
