<!-- Mon May 26 16:45:36 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcad3DPolyline" id="000000002b9d2ad8" desc="IAcad3DPolyline: AutoCAD 3dPolyline Interface" Application="IAcadApplication 000000013f512308" Closed="0" Coordinate="...Indexed contents not shown..." Coordinates="(21.4409 14.6498 0.0 20.8962 5.65378 0.0 ... )" Document="IAcadDocument 000000002b9fa338" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002bbc1838" Layer="0" Length="38.6446" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="42" ObjectID32="42" ObjectName="AcDb3dPolyline" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" TrueColor="IAcadAcCmColor 000000002bbc1b30" Type="0" Visible="-1" />
</DwgData>