<!-- Mon May 26 16:45:47 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadBlockReference" id="000000002bf07468" desc="IAcadBlockReference: AutoCAD Block Reference Interface" Application="IAcadApplication 000000013f512308" Document="IAcadDocument 000000002e969328" EffectiveName="First Block" EntityTransparency="ByLayer" Handle="1C8" HasAttributes="0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002eae92d8" InsertionPoint="(19.8219 8.45936 0.0)" InsUnits="Inches" InsUnitsFactor="1.0" IsDynamicBlock="0" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Name="First Block" Normal="(0.0 0.0 1.0)" ObjectID="48" ObjectID32="48" ObjectName="AcDbBlockReference" OwnerID="49" OwnerID32="49" PlotStyleName="ByLayer" Rotation="0.0" TrueColor="IAcadAcCmColor 000000002eae9810" Visible="-1" XEffectiveScaleFactor="1.0" XScaleFactor="1.0" YEffectiveScaleFactor="1.0" YScaleFactor="1.0" ZEffectiveScaleFactor="1.0" ZScaleFactor="1.0" />
</DwgData>