<!-- Mon May 26 16:46:19 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLine" id="0000000036eadb78" desc="IAcadLine: AutoCAD Line Interface" Angle="3.04252" Application="IAcadApplication 000000013f512308" Delta="(-22.6168 2.24807 0.0)" Document="IAcadDocument 0000000036e53b88" EndPoint="(9.75549 10.0432 0.0)" EntityTransparency="ByLayer" Handle="1CC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036c109b8" Layer="0" Length="22.7283" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="76" ObjectID32="76" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(32.3723 7.79514 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036c11190" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036eadc38" desc="IAcadLine: AutoCAD Line Interface" Angle="5.89039" Application="IAcadApplication 000000013f512308" Delta="(21.3416 -8.8424 0.0)" Document="IAcadDocument 0000000036e53b88" EndPoint="(32.3723 7.79514 0.0)" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000370c32e8" Layer="0" Length="23.1009" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="78" ObjectID32="78" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(11.0307 16.6375 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000370c3640" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036eadcf8" desc="IAcadLine: AutoCAD Line Interface" Angle="2.22385" Application="IAcadApplication 000000013f512308" Delta="(-10.577 13.8256 0.0)" Document="IAcadDocument 0000000036e53b88" EndPoint="(11.0307 16.6375 0.0)" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000370c3948" Layer="0" Length="17.4075" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="79" ObjectID32="79" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(21.6078 2.81192 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000370c3a00" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036eaddb8" desc="IAcadLine: AutoCAD Line Interface" Angle="4.17869" Application="IAcadApplication 000000013f512308" Delta="(-6.37622 -10.7907 0.0)" Document="IAcadDocument 0000000036e53b88" EndPoint="(21.6078 2.81192 0.0)" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000370c3e88" Layer="0" Length="12.5338" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="80" ObjectID32="80" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(27.984 13.6027 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000370c3be0" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036eade78" desc="IAcadLine: AutoCAD Line Interface" Angle="0.192841" Application="IAcadApplication 000000013f512308" Delta="(18.2285 3.55944 0.0)" Document="IAcadDocument 0000000036e53b88" EndPoint="(27.984 13.6027 0.0)" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000370c3fa8" Layer="0" Length="18.5728" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="81" ObjectID32="81" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(9.75549 10.0432 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000370c4000" Visible="-1" />
</DwgData>