[ AutoCAD - Mon May 26 16:46:28 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadMLine 000000002b9d8438>
; IAcadMLine: IAcadMLine Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (9.15538 14.989 0.0 18.7947 10.0057 0.0 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54018>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000372d6648>
;   Justification = 0
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   MLineScale = 1.0
;   ObjectID (RO) = 82
;   ObjectID32 (RO) = 82
;   ObjectName (RO) = "AcDbMline"
;   OwnerID (RO) = 83
;   OwnerID32 (RO) = 83
;   PlotStyleName = "ByLayer"
;   StyleName (RO) = "STANDARD"
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000372d63a0>
;   Visible = -1
