<!-- Mon May 26 16:46:33 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadPoint" id="00000000376d68d8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(16.5251 10.5127 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037586948" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="84" ObjectID32="84" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037586880" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6998" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(17.6111 9.23422 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037586b28" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="86" ObjectID32="86" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037586c40" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6a58" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(15.8658 5.35995 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037586e28" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="87" ObjectID32="87" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037586ac0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6b18" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(16.0985 6.05732 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037587068" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="88" ObjectID32="88" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037586fa0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6bd8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(19.2401 8.18816 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037587368" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="89" ObjectID32="89" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037587420" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6c98" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(21.1018 10.9776 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000375875a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="90" ObjectID32="90" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000375874e0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6d58" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(21.606 11.2488 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037587788" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="91" ObjectID32="91" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037587840" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6e18" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037587ae8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="92" ObjectID32="92" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037587a20" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6ed8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037587de8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="93" ObjectID32="93" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037587d20" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d6f98" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(19.3564 10.5515 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588028" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="94" ObjectID32="94" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037587f60" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d7058" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(18.891 11.7525 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588208" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="95" ObjectID32="95" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000375882c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d7118" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(27.928 8.65308 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588388" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="96" ObjectID32="96" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037588500" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d71d8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(19.6279 7.25834 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588868" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="97" ObjectID32="97" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000375888c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d7298" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(23.4289 11.9849 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588b08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="98" ObjectID32="98" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037588a40" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000376d7358" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f512308" Coordinates="(13.4999 11.4813 0.0)" Document="IAcadDocument 0000000036e54938" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037588e08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="99" ObjectID32="99" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037586760" Visible="-1" />
</DwgData>