[ AutoCAD - Mon May 26 16:46:33 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d68d8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (16.5251 10.5127 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CB"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037586948>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 84
;   ObjectID32 (RO) = 84
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037586880>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6998>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (17.6111 9.23422 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CA"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037586b28>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 86
;   ObjectID32 (RO) = 86
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037586c40>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6a58>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (15.8658 5.35995 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C9"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037586e28>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 87
;   ObjectID32 (RO) = 87
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037586ac0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6b18>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (16.0985 6.05732 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C8"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037587068>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 88
;   ObjectID32 (RO) = 88
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037586fa0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6bd8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (19.2401 8.18816 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C7"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037587368>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 89
;   ObjectID32 (RO) = 89
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037587420>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6c98>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (21.1018 10.9776 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C6"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000375875a8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 90
;   ObjectID32 (RO) = 90
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000375874e0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6d58>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (21.606 11.2488 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C5"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037587788>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 91
;   ObjectID32 (RO) = 91
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037587840>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6e18>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (21.7999 9.81536 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C4"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037587ae8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 92
;   ObjectID32 (RO) = 92
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037587a20>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6ed8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (21.7999 9.81536 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C3"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037587de8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 93
;   ObjectID32 (RO) = 93
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037587d20>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d6f98>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (19.3564 10.5515 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C2"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588028>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 94
;   ObjectID32 (RO) = 94
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037587f60>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d7058>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (18.891 11.7525 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588208>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 95
;   ObjectID32 (RO) = 95
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000375882c0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d7118>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (27.928 8.65308 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C0"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588388>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 96
;   ObjectID32 (RO) = 96
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037588500>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d71d8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (19.6279 7.25834 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588868>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 97
;   ObjectID32 (RO) = 97
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000375888c0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d7298>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (23.4289 11.9849 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588b08>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 98
;   ObjectID32 (RO) = 98
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037588a40>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000376d7358>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f512308>
;   Coordinates = (13.4999 11.4813 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036e54938>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000037588e08>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 99
;   ObjectID32 (RO) = 99
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000037586760>
;   Visible = -1
