<!-- Mon May 26 16:46:46 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000003a1f3d28" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="54.3027" Closed="0" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(9.00535 12.2913 17.1819 14.7267 20.7826 8.24476 ... )" Document="IAcadDocument 0000000037843208" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a2c7bb8" Layer="0" Length="32.2673" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="104" ObjectID32="104" ObjectName="AcDbPolyline" OwnerID="105" OwnerID32="105" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a2c7d90" Visible="-1" />
</DwgData>