<!-- Mon May 26 16:46:41 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="00000000376d9458" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="22.2834" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(5.92976 11.9915 6.24287 12.1103 6.53863 12.2675 ... )" Document="IAcadDocument 0000000036e55258" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037857548" Layer="0" Length="16.7449" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="100" ObjectID32="100" ObjectName="AcDbPolyline" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037857720" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="00000000376d9518" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="121.668" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(28.9217 8.88171 30.6459 5.29844 34.1471 3.41302 ... )" Document="IAcadDocument 0000000036e55258" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000378577e8" Layer="0" Length="39.7655" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="102" ObjectID32="102" ObjectName="AcDbPolyline" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037857ae0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="00000000376d9698" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="106.492" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.1081 10.4179 16.1916 14.1675 10.4882 8.74827 ... )" Document="IAcadDocument 0000000036e55258" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000037857ba8" Layer="0" Length="39.3372" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="103" ObjectID32="103" ObjectName="AcDbPolyline" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000037857ea0" Visible="-1" />
</DwgData>