<!-- Mon May 26 16:46:55 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000003a62eb78" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="30.5304" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )" Document="IAcadDocument 0000000037844448" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a856158" Layer="0" Length="26.5489" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="111" ObjectID32="111" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a856270" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a62ec38" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="25.9786" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )" Document="IAcadDocument 0000000037844448" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a8563f8" Layer="0" Length="23.4733" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="113" ObjectID32="113" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a8566f0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a62edb8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="39.634" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )" Document="IAcadDocument 0000000037844448" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a8567b8" Layer="0" Length="26.6957" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="114" ObjectID32="114" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a856ab0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a62ef38" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="44.2182" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )" Document="IAcadDocument 0000000037844448" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a856b78" Layer="0" Length="27.1381" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="115" ObjectID32="115" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a856e70" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a62eff8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f512308" Area="299.943" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )" Document="IAcadDocument 0000000037844448" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a856ff8" Layer="0" Length="78.293" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="116" ObjectID32="116" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a8572f0" Visible="-1" />
</DwgData>