<!-- Mon May 26 16:46:59 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadSpline" id="000000003a9aedf8" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013f512308" Area="45.4007" Closed="0" Closed2="0" ControlPoints="(4.09191 14.0523 0.0 7.35503 5.05999 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 0000000037844d68" EndTangent="AutoCAD.Application: General modeling failure" EntityTransparency="ByLayer" FitPoints="nil" FitTolerance="0.0" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003ab34368" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="15" Knots="(0.0 0.0 0.0 0.0 1.0 2.0 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="0" ObjectID="117" ObjectID32="117" ObjectName="AcDbSpline" OwnerID="118" OwnerID32="118" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="1" StartTangent="AutoCAD.Application: General modeling failure" TrueColor="IAcadAcCmColor 000000003ab343c0" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
<DwgEntity type="IAcadSpline" id="000000003a9af798" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013f512308" Area="20.1091" Closed="0" Closed2="0" ControlPoints="(28.059 8.80677 0.0 33.9643 7.72128 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 0000000037844d68" EndTangent="(0.0 0.0 0.0)" EntityTransparency="ByLayer" FitPoints="(28.059 8.80677 0.0 40.0613 6.22149 0.0 ... )" FitTolerance="1.0e-010" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003ab34308" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="0" Knots="(0.0 0.0 0.0 0.0 12.2776 26.0835 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="3" ObjectID="119" ObjectID32="119" ObjectName="AcDbSpline" OwnerID="118" OwnerID32="118" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="0" StartTangent="(0.0 0.0 0.0)" TrueColor="IAcadAcCmColor 000000003ab34420" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
<DwgEntity type="IAcadSpline" id="000000003a9af878" desc="IAcadSpline: AutoCAD Spline Interface" Application="IAcadApplication 000000013f512308" Area="46.2417" Closed="0" Closed2="0" ControlPoints="(10.018 7.4954 0.0 15.3906 6.25317 0.0 ... )" Degree="3" Degree2="3" Document="IAcadDocument 0000000037844d68" EndTangent="(0.0 0.0 0.0)" EntityTransparency="ByLayer" FitPoints="(10.018 7.4954 0.0 21.1577 6.37137 0.0 ... )" FitTolerance="1.0e-010" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003ab34968" IsPeriodic="0" IsPlanar="-1" IsRational="0" KnotParameterization="0" Knots="(0.0 0.0 0.0 0.0 11.1962 20.7142 ... )" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" NumberOfControlPoints="5" NumberOfFitPoints="3" ObjectID="120" ObjectID32="120" ObjectName="AcDbSpline" OwnerID="118" OwnerID32="118" PlotStyleName="ByLayer" SplineFrame="1" SplineMethod="0" StartTangent="(0.0 0.0 0.0)" TrueColor="IAcadAcCmColor 000000003ab34b40" Visible="-1" Weights="AutoCAD.Application: No weights available for polynomial spline" />
</DwgData>