<!-- Mon May 26 09:48:58 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcad3DPolyline" id="000000002bdd5268" desc="IAcad3DPolyline: AutoCAD 3dPolyline Interface" Application="IAcadApplication 000000013fd62308" Closed="0" Coordinate="...Indexed contents not shown..." Coordinates="(21.4409 14.6498 0.0 20.8962 5.65378 0.0 ... )" Document="IAcadDocument 000000002bdfdec8" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002dfbdd58" Layer="0" Length="38.6446" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="42" ObjectID32="42" ObjectName="AcDb3dPolyline" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" TrueColor="IAcadAcCmColor 000000002dfbde10" Type="0" Visible="-1" />
</DwgData>