<!-- Mon May 26 16:34:42 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadXline" id="0000000029e88fb8" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013f752308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.817977 0.575251 0.0)" Document="IAcadDocument 000000002cd60bd8" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002cf8adc8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="46" ObjectID32="46" ObjectName="AcDbXline" OwnerID="47" OwnerID32="47" PlotStyleName="ByLayer" SecondPoint="(33.866 49.0251 0.0)" TrueColor="IAcadAcCmColor 000000002cf8afa0" Visible="-1" />
<DwgEntity type="IAcadXline" id="0000000029e89488" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013f752308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.805537 -0.592545 0.0)" Document="IAcadDocument 000000002cd60bd8" EntityTransparency="ByLayer" Handle="1BC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002cf8b2a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="48" ObjectID32="48" ObjectName="AcDbXline" OwnerID="47" OwnerID32="47" PlotStyleName="ByLayer" SecondPoint="(33.8784 47.8573 0.0)" TrueColor="IAcadAcCmColor 000000002cf8b120" Visible="-1" />
<DwgEntity type="IAcadXline" id="0000000029e89748" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013f752308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.018621 -0.999827 0.0)" Document="IAcadDocument 000000002cd60bd8" EntityTransparency="ByLayer" Handle="1BB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002cf8b488" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="49" ObjectID32="49" ObjectName="AcDbXline" OwnerID="47" OwnerID32="47" PlotStyleName="ByLayer" SecondPoint="(34.6653 47.45 0.0)" TrueColor="IAcadAcCmColor 000000002cf8b600" Visible="-1" />
<DwgEntity type="IAcadXline" id="0000000029e89a08" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013f752308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(0.998718 0.050628 0.0)" Document="IAcadDocument 000000002cd60bd8" EntityTransparency="ByLayer" Handle="1BA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002cf8b788" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="50" ObjectID32="50" ObjectName="AcDbXline" OwnerID="47" OwnerID32="47" PlotStyleName="ByLayer" SecondPoint="(35.6827 48.5004 0.0)" TrueColor="IAcadAcCmColor 000000002cf8b4e0" Visible="-1" />
</DwgData>