<!-- Mon May 26 16:35:09 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000002d25fdb8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.158 3.59875 25.158 3.59875)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d2789d8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="51" ObjectID32="51" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27f030" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25fe78" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(16.3322 5.13493 21.3322 5.13493)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27f0f8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="53" ObjectID32="53" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27f390" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25ff38" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.1701 9.63106 23.1701 9.63106)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27f3f8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="54" ObjectID32="54" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27f5d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25fff8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.9831 11.0174 25.9831 11.0174)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27f6f8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="55" ObjectID32="55" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27f9f0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d2600b8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(26.7127 11.2826 31.7127 11.2826)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27fa58" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="56" ObjectID32="56" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27fd50" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d260178" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(29.0847 10.4928 34.0847 10.4928)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27f038" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="57" ObjectID32="57" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d27fab0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25fdb8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(31.3726 7.4954 36.3726 7.4954)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d27fe78" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="58" ObjectID32="58" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d2800b0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25fe78" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(27.2468 5.20986 32.2468 5.20986)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d280118" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="59" ObjectID32="59" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d2802f0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25ff38" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.3461 3.11167 28.3461 3.11167)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d280418" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="60" ObjectID32="60" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d280710" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d25fff8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.7212 12.7034 28.7212 12.7034)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d280778" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="61" ObjectID32="61" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d280a70" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002d2600b8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(14.907 8.58197 19.907 8.58197)" Document="IAcadDocument 000000002cea52d8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d280b38" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="62" ObjectID32="62" ObjectName="AcDbPolyline" OwnerID="52" OwnerID32="52" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002d280e30" Visible="-1" />
</DwgData>