<!-- Mon May 26 16:35:42 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadEllipse" id="0000000029e89a08" desc="IAcadEllipse: AutoCAD Ellipse Interface" Application="IAcadApplication 000000013f752308" Area="149.024" Center="(11.1433 9.5374 0.0)" Document="IAcadDocument 000000002a0804b8" EndAngle="6.28319" EndParameter="6.28319" EndPoint="(2.39246 1.50274 0.0)" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d4acfd8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" MajorAxis="(-8.7508 -8.03465 0.0)" MajorRadius="11.8799" Material="ByLayer" MinorAxis="(2.70052 -2.94122 0.0)" MinorRadius="3.99294" Normal="(0.0 0.0 1.0)" ObjectID="63" ObjectID32="63" ObjectName="AcDbEllipse" OwnerID="64" OwnerID32="64" PlotStyleName="ByLayer" RadiusRatio="0.336109" StartAngle="0.0" StartParameter="0.0" StartPoint="(2.39246 1.50274 0.0)" TrueColor="IAcadAcCmColor 000000002d4ad150" Visible="-1" />
<DwgEntity type="IAcadEllipse" id="0000000029e8b848" desc="IAcadEllipse: AutoCAD Ellipse Interface" Application="IAcadApplication 000000013f752308" Area="154.323" Center="(23.5581 9.96827 0.0)" Document="IAcadDocument 000000002a0804b8" EndAngle="6.28319" EndParameter="6.28319" EndPoint="(28.5452 1.52546 0.0)" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002d4b3338" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" MajorAxis="(4.98703 -8.44281 0.0)" MajorRadius="9.80569" Material="ByLayer" MinorAxis="(4.31333 2.54781 0.0)" MinorRadius="5.0096" Normal="(0.0 0.0 1.0)" ObjectID="65" ObjectID32="65" ObjectName="AcDbEllipse" OwnerID="64" OwnerID32="64" PlotStyleName="ByLayer" RadiusRatio="0.510888" StartAngle="0.0" StartParameter="0.0" StartPoint="(28.5452 1.52546 0.0)" TrueColor="IAcadAcCmColor 000000002d4b3390" Visible="-1" />
</DwgData>