[ AutoCAD - Mon May 26 16:36:01 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadHelix 0000000029e8b798>
; IAcadHelix: IAcadSpring Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   BaseRadius = 1.36885
;   Constrain = 1
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002ca47e78>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Height = 1.0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002d7e3b78>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   ObjectID (RO) = 66
;   ObjectID32 (RO) = 66
;   ObjectName (RO) = "AcDbHelix"
;   OwnerID (RO) = 67
;   OwnerID32 (RO) = 67
;   PlotStyleName = "ByLayer"
;   Position = (2.25405 13.3778 0.0)
;   TopRadius = 6.82783
;   TotalLength (RO) = 77.4916
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002d7e9cf0>
;   TurnHeight = 0.333333
;   Turns = 3.0
;   TurnSlope (RO) = 1.38962
;   Twist = 0
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadHelix 0000000029e8b848>
; IAcadHelix: IAcadSpring Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   BaseRadius = 1.42682
;   Constrain = 1
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002ca47e78>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Height = 1.0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002d7e9e78>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   ObjectID (RO) = 68
;   ObjectID32 (RO) = 68
;   ObjectName (RO) = "AcDbHelix"
;   OwnerID (RO) = 67
;   OwnerID32 (RO) = 67
;   PlotStyleName = "ByLayer"
;   Position = (34.5102 15.476 0.0)
;   TopRadius = 9.28195
;   TotalLength (RO) = 101.322
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002d7e9f90>
;   TurnHeight = 0.333333
;   Turns = 3.0
;   TurnSlope (RO) = 1.44417
;   Twist = 0
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadHelix 0000000029e8c138>
; IAcadHelix: IAcadSpring Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   BaseRadius = 5.23833
;   Constrain = 1
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002ca47e78>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Height = 1.0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002d7ea238>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   ObjectID (RO) = 69
;   ObjectID32 (RO) = 69
;   ObjectName (RO) = "AcDbHelix"
;   OwnerID (RO) = 67
;   OwnerID32 (RO) = 67
;   PlotStyleName = "ByLayer"
;   Position = (19.3948 11.0174 0.0)
;   TopRadius = 0.42723
;   TotalLength (RO) = 53.7246
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002d7ea590>
;   TurnHeight = 0.333333
;   Turns = 3.0
;   TurnSlope (RO) = -1.36586
;   Twist = 0
;   Visible = -1
