<!-- Mon May 26 16:36:01 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadHelix" id="0000000029e8b798" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013f752308" BaseRadius="1.36885" Constrain="1" Document="IAcadDocument 000000002ca47e78" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 000000002d7e3b78" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="66" ObjectID32="66" ObjectName="AcDbHelix" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Position="(2.25405 13.3778 0.0)" TopRadius="6.82783" TotalLength="77.4916" TrueColor="IAcadAcCmColor 000000002d7e9cf0" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.38962" Twist="0" Visible="-1" />
<DwgEntity type="IAcadHelix" id="0000000029e8b848" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013f752308" BaseRadius="1.42682" Constrain="1" Document="IAcadDocument 000000002ca47e78" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 000000002d7e9e78" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="68" ObjectID32="68" ObjectName="AcDbHelix" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Position="(34.5102 15.476 0.0)" TopRadius="9.28195" TotalLength="101.322" TrueColor="IAcadAcCmColor 000000002d7e9f90" TurnHeight="0.333333" Turns="3.0" TurnSlope="1.44417" Twist="0" Visible="-1" />
<DwgEntity type="IAcadHelix" id="0000000029e8c138" desc="IAcadHelix: IAcadSpring Interface" Application="IAcadApplication 000000013f752308" BaseRadius="5.23833" Constrain="1" Document="IAcadDocument 000000002ca47e78" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Height="1.0" Hyperlinks="IAcadHyperlinks 000000002d7ea238" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="69" ObjectID32="69" ObjectName="AcDbHelix" OwnerID="67" OwnerID32="67" PlotStyleName="ByLayer" Position="(19.3948 11.0174 0.0)" TopRadius="0.42723" TotalLength="53.7246" TrueColor="IAcadAcCmColor 000000002d7ea590" TurnHeight="0.333333" Turns="3.0" TurnSlope="-1.36586" Twist="0" Visible="-1" />
</DwgData>