[ AutoCAD - Mon May 26 16:36:36 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLine 0000000036284308>
; IAcadLine: AutoCAD Line Interface
; Property values:
;   Angle (RO) = 3.04252
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Delta (RO) = (-22.6168 2.24807 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d974fc8>
;   EndPoint = (9.75549 10.0432 0.0)
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CC"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000361ef9b8>
;   Layer = "0"
;   Length (RO) = 22.7283
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 70
;   ObjectID32 (RO) = 70
;   ObjectName (RO) = "AcDbLine"
;   OwnerID (RO) = 71
;   OwnerID32 (RO) = 71
;   PlotStyleName = "ByLayer"
;   StartPoint = (32.3723 7.79514 0.0)
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000361f5590>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLine 00000000362843c8>
; IAcadLine: AutoCAD Line Interface
; Property values:
;   Angle (RO) = 5.89039
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Delta (RO) = (21.3416 -8.8424 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d974fc8>
;   EndPoint = (32.3723 7.79514 0.0)
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CB"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000361f58f8>
;   Layer = "0"
;   Length (RO) = 23.1009
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 72
;   ObjectID32 (RO) = 72
;   ObjectName (RO) = "AcDbLine"
;   OwnerID (RO) = 71
;   OwnerID32 (RO) = 71
;   PlotStyleName = "ByLayer"
;   StartPoint = (11.0307 16.6375 0.0)
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000361f57d0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLine 0000000036284488>
; IAcadLine: AutoCAD Line Interface
; Property values:
;   Angle (RO) = 2.22385
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Delta (RO) = (-10.577 13.8256 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d974fc8>
;   EndPoint = (11.0307 16.6375 0.0)
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CA"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000361f5b98>
;   Layer = "0"
;   Length (RO) = 17.4075
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 73
;   ObjectID32 (RO) = 73
;   ObjectName (RO) = "AcDbLine"
;   OwnerID (RO) = 71
;   OwnerID32 (RO) = 71
;   PlotStyleName = "ByLayer"
;   StartPoint = (21.6078 2.81192 0.0)
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000361f5a70>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLine 0000000036284548>
; IAcadLine: AutoCAD Line Interface
; Property values:
;   Angle (RO) = 4.17869
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Delta (RO) = (-6.37622 -10.7907 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d974fc8>
;   EndPoint = (21.6078 2.81192 0.0)
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C9"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000361f5d18>
;   Layer = "0"
;   Length (RO) = 12.5338
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 74
;   ObjectID32 (RO) = 74
;   ObjectName (RO) = "AcDbLine"
;   OwnerID (RO) = 71
;   OwnerID32 (RO) = 71
;   PlotStyleName = "ByLayer"
;   StartPoint = (27.984 13.6027 0.0)
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000361f5dd0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLine 0000000036284608>
; IAcadLine: AutoCAD Line Interface
; Property values:
;   Angle (RO) = 0.192841
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Delta (RO) = (18.2285 3.55944 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d974fc8>
;   EndPoint = (27.984 13.6027 0.0)
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C8"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000361f61f8>
;   Layer = "0"
;   Length (RO) = 18.5728
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 75
;   ObjectID32 (RO) = 75
;   ObjectName (RO) = "AcDbLine"
;   OwnerID (RO) = 71
;   OwnerID32 (RO) = 71
;   PlotStyleName = "ByLayer"
;   StartPoint = (9.75549 10.0432 0.0)
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000361f62b0>
;   Visible = -1
