<!-- Mon May 26 16:36:36 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLine" id="0000000036284308" desc="IAcadLine: AutoCAD Line Interface" Angle="3.04252" Application="IAcadApplication 000000013f752308" Delta="(-22.6168 2.24807 0.0)" Document="IAcadDocument 000000002d974fc8" EndPoint="(9.75549 10.0432 0.0)" EntityTransparency="ByLayer" Handle="1CC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000361ef9b8" Layer="0" Length="22.7283" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="70" ObjectID32="70" ObjectName="AcDbLine" OwnerID="71" OwnerID32="71" PlotStyleName="ByLayer" StartPoint="(32.3723 7.79514 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000361f5590" Visible="-1" />
<DwgEntity type="IAcadLine" id="00000000362843c8" desc="IAcadLine: AutoCAD Line Interface" Angle="5.89039" Application="IAcadApplication 000000013f752308" Delta="(21.3416 -8.8424 0.0)" Document="IAcadDocument 000000002d974fc8" EndPoint="(32.3723 7.79514 0.0)" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000361f58f8" Layer="0" Length="23.1009" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="72" ObjectID32="72" ObjectName="AcDbLine" OwnerID="71" OwnerID32="71" PlotStyleName="ByLayer" StartPoint="(11.0307 16.6375 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000361f57d0" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036284488" desc="IAcadLine: AutoCAD Line Interface" Angle="2.22385" Application="IAcadApplication 000000013f752308" Delta="(-10.577 13.8256 0.0)" Document="IAcadDocument 000000002d974fc8" EndPoint="(11.0307 16.6375 0.0)" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000361f5b98" Layer="0" Length="17.4075" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="73" ObjectID32="73" ObjectName="AcDbLine" OwnerID="71" OwnerID32="71" PlotStyleName="ByLayer" StartPoint="(21.6078 2.81192 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000361f5a70" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036284548" desc="IAcadLine: AutoCAD Line Interface" Angle="4.17869" Application="IAcadApplication 000000013f752308" Delta="(-6.37622 -10.7907 0.0)" Document="IAcadDocument 000000002d974fc8" EndPoint="(21.6078 2.81192 0.0)" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000361f5d18" Layer="0" Length="12.5338" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="74" ObjectID32="74" ObjectName="AcDbLine" OwnerID="71" OwnerID32="71" PlotStyleName="ByLayer" StartPoint="(27.984 13.6027 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000361f5dd0" Visible="-1" />
<DwgEntity type="IAcadLine" id="0000000036284608" desc="IAcadLine: AutoCAD Line Interface" Angle="0.192841" Application="IAcadApplication 000000013f752308" Delta="(18.2285 3.55944 0.0)" Document="IAcadDocument 000000002d974fc8" EndPoint="(27.984 13.6027 0.0)" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000361f61f8" Layer="0" Length="18.5728" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="75" ObjectID32="75" ObjectName="AcDbLine" OwnerID="71" OwnerID32="71" PlotStyleName="ByLayer" StartPoint="(9.75549 10.0432 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000361f62b0" Visible="-1" />
</DwgData>