<!-- Mon May 26 16:37:37 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadPoint" id="000000003684b508" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(16.5251 10.5127 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787388" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="78" ObjectID32="78" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367874a0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b5c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(17.6111 9.23422 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787688" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="80" ObjectID32="80" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367875c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b688" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(15.8658 5.35995 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787988" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="81" ObjectID32="81" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036787740" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b748" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(16.0985 6.05732 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787c28" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="82" ObjectID32="82" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036787ce0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b808" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(19.2401 8.18816 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787e68" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="83" ObjectID32="83" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036787da0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b8c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(21.1018 10.9776 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036788108" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="84" ObjectID32="84" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036788040" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b988" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(21.606 11.2488 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367882e8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="85" ObjectID32="85" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367883a0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684ba48" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367886a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="86" ObjectID32="86" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367885e0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684bb08" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367888e8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="87" ObjectID32="87" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036788820" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684bbc8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(19.3564 10.5515 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036788b88" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="88" ObjectID32="88" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036788ac0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684bc88" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(18.891 11.7525 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036788c48" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="89" ObjectID32="89" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036788dc0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684bd48" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(27.928 8.65308 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367874a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="90" ObjectID32="90" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367890c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b508" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(19.6279 7.25834 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036787e68" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="91" ObjectID32="91" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036787da0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b5c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(23.4289 11.9849 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367888e8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="92" ObjectID32="92" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367886a0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003684b688" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013f752308" Coordinates="(13.4999 11.4813 0.0)" Document="IAcadDocument 000000002d975d78" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036789128" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="93" ObjectID32="93" ObjectName="AcDbPoint" OwnerID="79" OwnerID32="79" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367872c0" Visible="-1" />
</DwgData>