[ AutoCAD - Mon May 26 16:37:44 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003684dfc8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 22.2834
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (5.92976 11.9915 6.24287 12.1103 6.53863 12.2675 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d976698>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000036a8af08>
;   Layer = "0"
;   Length (RO) = 16.7449
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 94
;   ObjectID32 (RO) = 94
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 95
;   OwnerID32 (RO) = 95
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000036a911a0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003684e088>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 121.668
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (28.9217 8.88171 30.6459 5.29844 34.1471 3.41302 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d976698>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000036a91208>
;   Layer = "0"
;   Length (RO) = 39.7655
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 96
;   ObjectID32 (RO) = 96
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 95
;   OwnerID32 (RO) = 95
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000036a91620>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003684e208>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 106.492
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (23.1081 10.4179 16.1916 14.1675 10.4882 8.74827 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002d976698>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 0000000036a91388>
;   Layer = "0"
;   Length (RO) = 39.3372
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 97
;   ObjectID32 (RO) = 97
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 95
;   OwnerID32 (RO) = 95
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000036a918c0>
;   Visible = -1
