<!-- Mon May 26 16:37:44 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000003684dfc8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="22.2834" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(5.92976 11.9915 6.24287 12.1103 6.53863 12.2675 ... )" Document="IAcadDocument 000000002d976698" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036a8af08" Layer="0" Length="16.7449" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="94" ObjectID32="94" ObjectName="AcDbPolyline" OwnerID="95" OwnerID32="95" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036a911a0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003684e088" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="121.668" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(28.9217 8.88171 30.6459 5.29844 34.1471 3.41302 ... )" Document="IAcadDocument 000000002d976698" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036a91208" Layer="0" Length="39.7655" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="96" ObjectID32="96" ObjectName="AcDbPolyline" OwnerID="95" OwnerID32="95" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036a91620" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003684e208" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="106.492" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.1081 10.4179 16.1916 14.1675 10.4882 8.74827 ... )" Document="IAcadDocument 000000002d976698" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036a91388" Layer="0" Length="39.3372" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="97" ObjectID32="97" ObjectName="AcDbPolyline" OwnerID="95" OwnerID32="95" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036a918c0" Visible="-1" />
</DwgData>