<!-- Mon May 26 16:37:59 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadRay" id="0000000029e90338" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013f752308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 -1.0 0.0)" Document="IAcadDocument 00000000367b2f18" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c6b0308" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="100" ObjectID32="100" ObjectName="AcDbRay" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" SecondPoint="(10.0931 9.19308 0.0)" TrueColor="IAcadAcCmColor 000000003c6b5fa0" Visible="-1" />
<DwgEntity type="IAcadRay" id="0000000029e903e8" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013f752308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 1.0 0.0)" Document="IAcadDocument 00000000367b2f18" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c6b6188" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="102" ObjectID32="102" ObjectName="AcDbRay" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" SecondPoint="(10.0931 11.1931 0.0)" TrueColor="IAcadAcCmColor 000000003c6b6240" Visible="-1" />
<DwgEntity type="IAcadRay" id="0000000029e906a8" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013f752308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.983378 -0.181571 0.0)" Document="IAcadDocument 00000000367b2f18" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c6b63c8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="103" ObjectID32="103" ObjectName="AcDbRay" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" SecondPoint="(11.0764 10.0115 0.0)" TrueColor="IAcadAcCmColor 000000003c6b65a0" Visible="-1" />
<DwgEntity type="IAcadRay" id="0000000029e90968" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013f752308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.98609 0.166213 0.0)" Document="IAcadDocument 00000000367b2f18" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c6b68a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="104" ObjectID32="104" ObjectName="AcDbRay" OwnerID="101" OwnerID32="101" PlotStyleName="ByLayer" SecondPoint="(11.0791 10.3593 0.0)" TrueColor="IAcadAcCmColor 000000003c6b6600" Visible="-1" />
</DwgData>