<!-- Mon May 26 16:38:06 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="0000000036dd5b88" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="30.5304" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )" Document="IAcadDocument 00000000367b33a8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c973318" Layer="0" Length="26.5489" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="105" ObjectID32="105" ObjectName="AcDbPolyline" OwnerID="106" OwnerID32="106" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003c9792b0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000036dd5c48" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="25.9786" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )" Document="IAcadDocument 00000000367b33a8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c979378" Layer="0" Length="23.4733" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="107" ObjectID32="107" ObjectName="AcDbPolyline" OwnerID="106" OwnerID32="106" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003c979670" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000036dd5dc8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="39.634" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )" Document="IAcadDocument 00000000367b33a8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c979738" Layer="0" Length="26.6957" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="108" ObjectID32="108" ObjectName="AcDbPolyline" OwnerID="106" OwnerID32="106" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003c979af0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000036dd5f48" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="44.2182" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )" Document="IAcadDocument 00000000367b33a8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c979b58" Layer="0" Length="27.1381" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="109" ObjectID32="109" ObjectName="AcDbPolyline" OwnerID="106" OwnerID32="106" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003c979e50" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="0000000036dd87c8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013f752308" Area="299.943" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )" Document="IAcadDocument 00000000367b33a8" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003c979eb8" Layer="0" Length="78.293" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="110" ObjectID32="110" ObjectName="AcDbPolyline" OwnerID="106" OwnerID32="106" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003c97a0f0" Visible="-1" />
</DwgData>