[ AutoCAD - Mon May 26 16:38:06 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 0000000036dd5b88>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 30.5304
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000367b33a8>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003c973318>
;   Layer = "0"
;   Length (RO) = 26.5489
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 105
;   ObjectID32 (RO) = 105
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 106
;   OwnerID32 (RO) = 106
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003c9792b0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 0000000036dd5c48>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 25.9786
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000367b33a8>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C0"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003c979378>
;   Layer = "0"
;   Length (RO) = 23.4733
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 107
;   ObjectID32 (RO) = 107
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 106
;   OwnerID32 (RO) = 106
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003c979670>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 0000000036dd5dc8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 39.634
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000367b33a8>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003c979738>
;   Layer = "0"
;   Length (RO) = 26.6957
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 108
;   ObjectID32 (RO) = 108
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 106
;   OwnerID32 (RO) = 106
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003c979af0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 0000000036dd5f48>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 44.2182
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000367b33a8>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003c979b58>
;   Layer = "0"
;   Length (RO) = 27.1381
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 109
;   ObjectID32 (RO) = 109
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 106
;   OwnerID32 (RO) = 106
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003c979e50>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 0000000036dd87c8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013f752308>
;   Area (RO) = 299.943
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000367b33a8>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003c979eb8>
;   Layer = "0"
;   Length (RO) = 78.293
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 110
;   ObjectID32 (RO) = 110
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 106
;   OwnerID32 (RO) = 106
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003c97a0f0>
;   Visible = -1
