<!-- Mon May 26 16:38:51 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadTable" id="000000002c341238" desc="IAcadTable: IAcadTable Interface" AllowManualHeights="0" AllowManualPositions="0" Application="IAcadApplication 000000013f752308" BreaksEnabled="0" BreakSpacing="0.99" Columns="3" ColumnWidth="...Indexed contents not shown..." Direction="(1.0 0.0 0.0)" Document="IAcadDocument 000000002bd9eac8" EnableBreak="...Indexed contents not shown..." EntityTransparency="ByLayer" FlowDirection="0" Handle="1BE" HasExtensionDictionary="0" HasSubSelection="0" HeaderSuppressed="0" Height="1.46625" HorzCellMargin="0.06" Hyperlinks="IAcadHyperlinks 000000002e4adad8" InsertionPoint="(13.8101 11.2876 0.0)" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" MinimumTableHeight="1.46625" MinimumTableWidth="1.11" ObjectID="42" ObjectID32="42" ObjectName="AcDbTable" OwnerID="43" OwnerID32="43" PlotStyleName="ByLayer" RegenerateTableSuppressed="0" RepeatBottomLabels="0" RepeatTopLabels="0" RowHeight="...Indexed contents not shown..." Rows="3" StyleName="Standard" TableBreakFlowDirection="1" TableBreakHeight="0.0" TableStyleOverrides="nil" TitleSuppressed="0" TrueColor="IAcadAcCmColor 000000002e4adfb0" VertCellMargin="0.06" Visible="-1" Width="7.5" />
</DwgData>