<!-- Mon May 26 16:38:57 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadMText" id="000000002c04cbc8" desc="IAcadMText: AutoCAD MText Interface" Application="IAcadApplication 000000013f752308" AttachmentPoint="1" BackgroundFill="0" Document="IAcadDocument 000000002c33c488" DrawingDirection="5" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Height="0.2" Hyperlinks="IAcadHyperlinks 000000002e607cd8" InsertionPoint="(7.33298 14.1158 0.0)" Layer="0" LineSpacingDistance="0.333333" LineSpacingFactor="1.0" LineSpacingStyle="1" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="44" ObjectID32="44" ObjectName="AcDbMText" OwnerID="45" OwnerID32="45" PlotStyleName="ByLayer" Rotation="0.0" StyleName="Standard" TextString="This a multiline text to check if libredwg is able to read this in the current file format version" TrueColor="IAcadAcCmColor 000000002c02d2f0" Visible="-1" Width="13.0319" />
</DwgData>