<!-- Mon May 26 16:48:36 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000002f49a068" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.158 3.59875 25.158 3.59875)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d5ff8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="57" ObjectID32="57" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d62f0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a128" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(16.3322 5.13493 21.3322 5.13493)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d6358" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="59" ObjectID32="59" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d66b0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a1e8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.1701 9.63106 23.1701 9.63106)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d6778" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="60" ObjectID32="60" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d6a10" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a2a8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.9831 11.0174 25.9831 11.0174)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d6a78" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="61" ObjectID32="61" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d6c50" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a368" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(26.7127 11.2826 31.7127 11.2826)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d6d78" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="62" ObjectID32="62" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d7070" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a428" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(29.0847 10.4928 34.0847 10.4928)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d70d8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="63" ObjectID32="63" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d73d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a4e8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(31.3726 7.4954 36.3726 7.4954)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d62f8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="64" ObjectID32="64" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d70d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a068" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(27.2468 5.20986 32.2468 5.20986)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d7258" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="65" ObjectID32="65" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d76d0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a128" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.3461 3.11167 28.3461 3.11167)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d75b8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="66" ObjectID32="66" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d7970" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a1e8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.7212 12.7034 28.7212 12.7034)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d79d8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="67" ObjectID32="67" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d7cd0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f49a2a8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(14.907 8.58197 19.907 8.58197)" Document="IAcadDocument 000000002f226708" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f2d7d38" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="68" ObjectID32="68" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f2d8030" Visible="-1" />
</DwgData>