<!-- Mon May 26 16:49:14 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadPoint" id="00000000372b39b8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(16.5251 10.5127 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371ba558" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="84" ObjectID32="84" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371ba670" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3a78" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(17.6111 9.23422 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371ba858" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="86" ObjectID32="86" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371ba970" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3b38" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(15.8658 5.35995 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bab58" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="87" ObjectID32="87" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371ba7f0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3bf8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(16.0985 6.05732 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371badf8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="88" ObjectID32="88" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371babb0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3cb8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(19.2401 8.18816 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bb098" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="89" ObjectID32="89" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bb150" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3d78" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(21.1018 10.9776 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bb2d8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="90" ObjectID32="90" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bb210" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3e38" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(21.606 11.2488 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bb4b8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="91" ObjectID32="91" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bb570" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3ef8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bb818" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="92" ObjectID32="92" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bb750" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b3fb8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bbb18" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="93" ObjectID32="93" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bba50" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b4078" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(19.3564 10.5515 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bbd58" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="94" ObjectID32="94" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bbc90" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b4138" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(18.891 11.7525 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bbf38" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="95" ObjectID32="95" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bbff0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b41f8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(27.928 8.65308 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bc0b8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="96" ObjectID32="96" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bc230" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b42b8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(19.6279 7.25834 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bc598" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="97" ObjectID32="97" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bc5f0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b4378" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(23.4289 11.9849 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bc838" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="98" ObjectID32="98" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371bc770" Visible="-1" />
<DwgEntity type="IAcadPoint" id="00000000372b4438" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013ffe2308" Coordinates="(13.4999 11.4813 0.0)" Document="IAcadDocument 0000000036a4f5a8" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000371bcb38" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="99" ObjectID32="99" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000371ba490" Visible="-1" />
</DwgData>