[ AutoCAD - Mon May 26 16:49:14 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b39b8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (16.5251 10.5127 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CB"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371ba558>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 84
;   ObjectID32 (RO) = 84
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371ba670>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3a78>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (17.6111 9.23422 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CA"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371ba858>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 86
;   ObjectID32 (RO) = 86
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371ba970>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3b38>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (15.8658 5.35995 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C9"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bab58>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 87
;   ObjectID32 (RO) = 87
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371ba7f0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3bf8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (16.0985 6.05732 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C8"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371badf8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 88
;   ObjectID32 (RO) = 88
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371babb0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3cb8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (19.2401 8.18816 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C7"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bb098>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 89
;   ObjectID32 (RO) = 89
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bb150>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3d78>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (21.1018 10.9776 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C6"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bb2d8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 90
;   ObjectID32 (RO) = 90
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bb210>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3e38>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (21.606 11.2488 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C5"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bb4b8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 91
;   ObjectID32 (RO) = 91
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bb570>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3ef8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (21.7999 9.81536 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C4"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bb818>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 92
;   ObjectID32 (RO) = 92
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bb750>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b3fb8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (21.7999 9.81536 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C3"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bbb18>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 93
;   ObjectID32 (RO) = 93
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bba50>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b4078>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (19.3564 10.5515 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C2"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bbd58>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 94
;   ObjectID32 (RO) = 94
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bbc90>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b4138>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (18.891 11.7525 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bbf38>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 95
;   ObjectID32 (RO) = 95
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bbff0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b41f8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (27.928 8.65308 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C0"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bc0b8>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 96
;   ObjectID32 (RO) = 96
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bc230>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b42b8>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (19.6279 7.25834 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bc598>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 97
;   ObjectID32 (RO) = 97
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bc5f0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b4378>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (23.4289 11.9849 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bc838>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 98
;   ObjectID32 (RO) = 98
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371bc770>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadPoint 00000000372b4438>
; IAcadPoint: AutoCAD Point Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013ffe2308>
;   Coordinates = (13.4999 11.4813 0.0)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 0000000036a4f5a8>
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 00000000371bcb38>
;   Layer = "0"
;   Linetype = "ByLayer"
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 99
;   ObjectID32 (RO) = 99
;   ObjectName (RO) = "AcDbPoint"
;   OwnerID (RO) = 85
;   OwnerID32 (RO) = 85
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 00000000371ba490>
;   Visible = -1
