<!-- Mon May 26 16:49:24 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000003749fc68" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013ffe2308" Area="54.3027" Closed="0" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(9.00535 12.2913 17.1819 14.7267 20.7826 8.24476 ... )" Document="IAcadDocument 00000000371e3548" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000039c02518" Layer="0" Length="32.2673" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="104" ObjectID32="104" ObjectName="AcDbPolyline" OwnerID="105" OwnerID32="105" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000039c026f0" Visible="-1" />
</DwgData>