<!-- Mon May 26 16:49:28 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadRay" id="000000003a035278" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013ffe2308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 -1.0 0.0)" Document="IAcadDocument 00000000371e3e68" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000039eb8198" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="106" ObjectID32="106" ObjectName="AcDbRay" OwnerID="107" OwnerID32="107" PlotStyleName="ByLayer" SecondPoint="(10.0931 9.19308 0.0)" TrueColor="IAcadAcCmColor 0000000039eb7ef0" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000003a0351c8" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013ffe2308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.0 1.0 0.0)" Document="IAcadDocument 00000000371e3e68" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000039eb8498" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="108" ObjectID32="108" ObjectName="AcDbRay" OwnerID="107" OwnerID32="107" PlotStyleName="ByLayer" SecondPoint="(10.0931 11.1931 0.0)" TrueColor="IAcadAcCmColor 0000000039eb84f0" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000003a035538" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013ffe2308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.983378 -0.181571 0.0)" Document="IAcadDocument 00000000371e3e68" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000039eb8738" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="109" ObjectID32="109" ObjectName="AcDbRay" OwnerID="107" OwnerID32="107" PlotStyleName="ByLayer" SecondPoint="(11.0764 10.0115 0.0)" TrueColor="IAcadAcCmColor 0000000039eb86d0" Visible="-1" />
<DwgEntity type="IAcadRay" id="000000003a0357f8" desc="IAcadRay: AutoCAD Ray Interface" Application="IAcadApplication 000000013ffe2308" BasePoint="(10.0931 10.1931 0.0)" DirectionVector="(0.98609 0.166213 0.0)" Document="IAcadDocument 00000000371e3e68" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000039eb8a38" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="110" ObjectID32="110" ObjectName="AcDbRay" OwnerID="107" OwnerID32="107" PlotStyleName="ByLayer" SecondPoint="(11.0791 10.3593 0.0)" TrueColor="IAcadAcCmColor 0000000039eb8b50" Visible="-1" />
</DwgData>