<!-- Mon May 26 16:49:49 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadMText" id="000000003a849708" desc="IAcadMText: AutoCAD MText Interface" Application="IAcadApplication 000000013ffe2308" AttachmentPoint="1" BackgroundFill="0" Document="IAcadDocument 00000000371e62e8" DrawingDirection="5" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Height="0.2" Hyperlinks="IAcadHyperlinks 000000003e8875e8" InsertionPoint="(7.33298 14.1158 0.0)" Layer="0" LineSpacingDistance="0.333333" LineSpacingFactor="1.0" LineSpacingStyle="1" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="123" ObjectID32="123" ObjectName="AcDbMText" OwnerID="124" OwnerID32="124" PlotStyleName="ByLayer" Rotation="0.0" StyleName="Standard" TextString="This a multiline text to check if libredwg is able to read this in the current file format version" TrueColor="IAcadAcCmColor 000000003e8878e0" Visible="-1" Width="13.0319" />
</DwgData>