<!-- Mon May 26 16:43:08 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadCircle" id="000000002eee5068" desc="IAcadCircle: AutoCAD Circle Interface" Application="IAcadApplication 000000013fa12308" Area="575.138" Center="(23.4493 -1.09239 0.0)" Circumference="85.0141" Diameter="27.0608" Document="IAcadDocument 000000002eb81838" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002ee41e28" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="50" ObjectID32="50" ObjectName="AcDbCircle" OwnerID="51" OwnerID32="51" PlotStyleName="ByLayer" Radius="13.5304" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002ee41d00" Visible="-1" />
</DwgData>