<!-- Mon May 26 16:43:14 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadXline" id="000000002b6794b8" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.817977 0.575251 0.0)" Document="IAcadDocument 000000002ee7cf38" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f0f94b8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="52" ObjectID32="52" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(33.866 49.0251 0.0)" TrueColor="IAcadAcCmColor 000000002f0f9690" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002b679568" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.805537 -0.592545 0.0)" Document="IAcadDocument 000000002ee7cf38" EntityTransparency="ByLayer" Handle="1BC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f0f9938" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="54" ObjectID32="54" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(33.8784 47.8573 0.0)" TrueColor="IAcadAcCmColor 000000002f0f97b0" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002b679828" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(-0.018621 -0.999827 0.0)" Document="IAcadDocument 000000002ee7cf38" EntityTransparency="ByLayer" Handle="1BB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f0f9b78" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="55" ObjectID32="55" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(34.6653 47.45 0.0)" TrueColor="IAcadAcCmColor 000000002f0f99f0" Visible="-1" />
<DwgEntity type="IAcadXline" id="000000002b679ae8" desc="IAcadXline: AutoCAD Xline Interface" Application="IAcadApplication 000000013fa12308" BasePoint="(34.684 48.4498 0.0)" DirectionVector="(0.998718 0.050628 0.0)" Document="IAcadDocument 000000002ee7cf38" EntityTransparency="ByLayer" Handle="1BA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f0f9ed8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" ObjectID="56" ObjectID32="56" ObjectName="AcDbXline" OwnerID="53" OwnerID32="53" PlotStyleName="ByLayer" SecondPoint="(35.6827 48.5004 0.0)" TrueColor="IAcadAcCmColor 000000002f0f9d50" Visible="-1" />
</DwgData>