<!-- Mon May 26 16:43:45 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000002f5a40c8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.158 3.59875 25.158 3.59875)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3da488" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="57" ObjectID32="57" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3da780" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4188" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(16.3322 5.13493 21.3322 5.13493)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3da7e8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="59" ObjectID32="59" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3dab40" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4248" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.1701 9.63106 23.1701 9.63106)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3dac08" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="60" ObjectID32="60" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3daea0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4308" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(20.9831 11.0174 25.9831 11.0174)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3daf08" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="61" ObjectID32="61" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3db0e0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a43c8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(26.7127 11.2826 31.7127 11.2826)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3db208" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="62" ObjectID32="62" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3db500" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4488" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(29.0847 10.4928 34.0847 10.4928)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3db568" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="63" ObjectID32="63" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3db860" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4548" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(31.3726 7.4954 36.3726 7.4954)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3da788" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="64" ObjectID32="64" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3db560" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a40c8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(27.2468 5.20986 32.2468 5.20986)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3db6e8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="65" ObjectID32="65" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3dbb60" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4188" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.3461 3.11167 28.3461 3.11167)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3dba48" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="66" ObjectID32="66" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3dbe00" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4248" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(23.7212 12.7034 28.7212 12.7034)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3dbe68" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="67" ObjectID32="67" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3dc160" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000002f5a4308" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="19.635" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(14.907 8.58197 19.907 8.58197)" Document="IAcadDocument 000000002f2ee688" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000002f3dc1c8" Layer="0" Length="15.708" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="68" ObjectID32="68" ObjectName="AcDbPolyline" OwnerID="58" OwnerID32="58" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000002f3dc4c0" Visible="-1" />
</DwgData>