[ AutoCAD - Mon May 26 16:43:45 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a40c8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (20.158 3.59875 25.158 3.59875)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1CA"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3da488>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 57
;   ObjectID32 (RO) = 57
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3da780>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4188>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (16.3322 5.13493 21.3322 5.13493)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C9"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3da7e8>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 59
;   ObjectID32 (RO) = 59
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3dab40>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4248>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (18.1701 9.63106 23.1701 9.63106)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C8"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3dac08>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 60
;   ObjectID32 (RO) = 60
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3daea0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4308>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (20.9831 11.0174 25.9831 11.0174)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C7"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3daf08>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 61
;   ObjectID32 (RO) = 61
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3db0e0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a43c8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (26.7127 11.2826 31.7127 11.2826)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C6"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3db208>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 62
;   ObjectID32 (RO) = 62
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3db500>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4488>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (29.0847 10.4928 34.0847 10.4928)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C5"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3db568>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 63
;   ObjectID32 (RO) = 63
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3db860>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4548>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (31.3726 7.4954 36.3726 7.4954)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C4"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3da788>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 64
;   ObjectID32 (RO) = 64
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3db560>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a40c8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (27.2468 5.20986 32.2468 5.20986)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C3"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3db6e8>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 65
;   ObjectID32 (RO) = 65
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3dbb60>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4188>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (23.3461 3.11167 28.3461 3.11167)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C2"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3dba48>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 66
;   ObjectID32 (RO) = 66
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3dbe00>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4248>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (23.7212 12.7034 28.7212 12.7034)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3dbe68>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 67
;   ObjectID32 (RO) = 67
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3dc160>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000002f5a4308>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 19.635
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (14.907 8.58197 19.907 8.58197)
;   Document (RO) = #<VLA-OBJECT IAcadDocument 000000002f2ee688>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C0"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000002f3dc1c8>
;   Layer = "0"
;   Length (RO) = 15.708
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 68
;   ObjectID32 (RO) = 68
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 58
;   OwnerID32 (RO) = 58
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000002f3dc4c0>
;   Visible = -1
