<!-- Mon May 26 16:44:08 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLine" id="000000003613d338" desc="IAcadLine: AutoCAD Line Interface" Angle="3.04252" Application="IAcadApplication 000000013fa12308" Delta="(-22.6168 2.24807 0.0)" Document="IAcadDocument 000000003604ad18" EndPoint="(9.75549 10.0432 0.0)" EntityTransparency="ByLayer" Handle="1CC" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036235348" Layer="0" Length="22.7283" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="76" ObjectID32="76" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(32.3723 7.79514 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000362355e0" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000003613d3f8" desc="IAcadLine: AutoCAD Line Interface" Angle="5.89039" Application="IAcadApplication 000000013fa12308" Delta="(21.3416 -8.8424 0.0)" Document="IAcadDocument 000000003604ad18" EndPoint="(32.3723 7.79514 0.0)" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036235648" Layer="0" Length="23.1009" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="78" ObjectID32="78" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(11.0307 16.6375 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036235940" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000003613d4b8" desc="IAcadLine: AutoCAD Line Interface" Angle="2.22385" Application="IAcadApplication 000000013fa12308" Delta="(-10.577 13.8256 0.0)" Document="IAcadDocument 000000003604ad18" EndPoint="(11.0307 16.6375 0.0)" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036235ca8" Layer="0" Length="17.4075" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="79" ObjectID32="79" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(21.6078 2.81192 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036235d60" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000003613d578" desc="IAcadLine: AutoCAD Line Interface" Angle="4.17869" Application="IAcadApplication 000000013fa12308" Delta="(-6.37622 -10.7907 0.0)" Document="IAcadDocument 000000003604ad18" EndPoint="(21.6078 2.81192 0.0)" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 0000000036236188" Layer="0" Length="12.5338" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="80" ObjectID32="80" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(27.984 13.6027 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036236000" Visible="-1" />
<DwgEntity type="IAcadLine" id="000000003613d638" desc="IAcadLine: AutoCAD Line Interface" Angle="0.192841" Application="IAcadApplication 000000013fa12308" Delta="(18.2285 3.55944 0.0)" Document="IAcadDocument 000000003604ad18" EndPoint="(27.984 13.6027 0.0)" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000362362a8" Layer="0" Length="18.5728" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="81" ObjectID32="81" ObjectName="AcDbLine" OwnerID="77" OwnerID32="77" PlotStyleName="ByLayer" StartPoint="(9.75549 10.0432 0.0)" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000036236300" Visible="-1" />
</DwgData>