<!-- Mon May 26 16:44:22 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadPoint" id="000000003682a248" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(16.5251 10.5127 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1CB" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c2ca8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="84" ObjectID32="84" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c2dc0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a308" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(17.6111 9.23422 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1CA" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c2fa8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="86" ObjectID32="86" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c30c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a3c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(15.8658 5.35995 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C9" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c3248" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="87" ObjectID32="87" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c2f40" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a488" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(16.0985 6.05732 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C8" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c3488" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="88" ObjectID32="88" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c33c0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a548" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.2401 8.18816 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C7" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c3788" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="89" ObjectID32="89" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c3840" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a608" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.1018 10.9776 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C6" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c39c8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="90" ObjectID32="90" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c3900" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a6c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.606 11.2488 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C5" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c3ba8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="91" ObjectID32="91" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c3c60" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a788" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C4" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c3f08" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="92" ObjectID32="92" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c3e40" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a848" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(21.7999 9.81536 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C3" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c4208" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="93" ObjectID32="93" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c4140" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a908" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.3564 10.5515 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C2" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c4448" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="94" ObjectID32="94" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c4380" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682a9c8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(18.891 11.7525 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c4628" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="95" ObjectID32="95" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c46e0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682aa88" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(27.928 8.65308 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c47a8" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="96" ObjectID32="96" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c4920" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682ab48" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(19.6279 7.25834 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c4c88" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="97" ObjectID32="97" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c4ce0" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682ac08" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(23.4289 11.9849 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c4f28" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="98" ObjectID32="98" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c4e60" Visible="-1" />
<DwgEntity type="IAcadPoint" id="000000003682acc8" desc="IAcadPoint: AutoCAD Point Interface" Application="IAcadApplication 000000013fa12308" Coordinates="(13.4999 11.4813 0.0)" Document="IAcadDocument 00000000364d00e8" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 00000000367c5228" Layer="0" Linetype="ByLayer" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="99" ObjectID32="99" ObjectName="AcDbPoint" OwnerID="85" OwnerID32="85" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 00000000367c2b80" Visible="-1" />
</DwgData>