<!-- Mon May 26 16:44:48 2014  --><?xml version="1.0" encoding="UTF-8"?>
<DwgData>
<DwgEntity type="IAcadLWPolyline" id="000000003a03ccd8" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="30.5304" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )" Document="IAcadDocument 00000000364d2568" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C1" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a1936c8" Layer="0" Length="26.5489" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="111" ObjectID32="111" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 0000000039eb58e0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a03cd98" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="25.9786" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )" Document="IAcadDocument 00000000364d2568" Elevation="0.0" EntityTransparency="ByLayer" Handle="1C0" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a39b5c8" Layer="0" Length="23.4733" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="113" ObjectID32="113" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a39b920" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a03cf18" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="39.634" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )" Document="IAcadDocument 00000000364d2568" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BF" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a39b9e8" Layer="0" Length="26.6957" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="114" ObjectID32="114" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a39bce0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a03d098" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="44.2182" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )" Document="IAcadDocument 00000000364d2568" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BE" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a39bda8" Layer="0" Length="27.1381" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="115" ObjectID32="115" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a39c0a0" Visible="-1" />
<DwgEntity type="IAcadLWPolyline" id="000000003a03d158" desc="IAcadLWPolyline: AutoCAD Lightweight Polyline Interface" Application="IAcadApplication 000000013fa12308" Area="299.943" Closed="-1" ConstantWidth="0.0" Coordinate="...Indexed contents not shown..." Coordinates="(10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )" Document="IAcadDocument 00000000364d2568" Elevation="0.0" EntityTransparency="ByLayer" Handle="1BD" HasExtensionDictionary="0" Hyperlinks="IAcadHyperlinks 000000003a39c228" Layer="0" Length="78.293" Linetype="ByLayer" LinetypeGeneration="0" LinetypeScale="1.0" Lineweight="-1" Material="ByLayer" Normal="(0.0 0.0 1.0)" ObjectID="116" ObjectID32="116" ObjectName="AcDbPolyline" OwnerID="112" OwnerID32="112" PlotStyleName="ByLayer" Thickness="0.0" TrueColor="IAcadAcCmColor 000000003a39c520" Visible="-1" />
</DwgData>