[ AutoCAD - Mon May 26 16:44:48 2014  ]----------------------------------------

<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003a03ccd8>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 30.5304
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (18.7197 2.73699 29.0342 2.73699 29.0342 -0.222969 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000364d2568>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C1"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003a1936c8>
;   Layer = "0"
;   Length (RO) = 26.5489
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 111
;   ObjectID32 (RO) = 111
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 112
;   OwnerID32 (RO) = 112
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 0000000039eb58e0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003a03cd98>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 25.9786
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (17.9696 17.4618 26.7463 17.4618 26.7463 14.5019 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000364d2568>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1C0"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003a39b5c8>
;   Layer = "0"
;   Length (RO) = 23.4733
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 113
;   ObjectID32 (RO) = 113
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 112
;   OwnerID32 (RO) = 112
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003a39b920>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003a03cf18>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 39.634
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (18.9448 10.7551 27.834 10.7551 27.834 6.29643 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000364d2568>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BF"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003a39b9e8>
;   Layer = "0"
;   Length (RO) = 26.6957
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 114
;   ObjectID32 (RO) = 114
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 112
;   OwnerID32 (RO) = 112
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003a39bce0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003a03d098>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 44.2182
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (2.36657 13.1905 7.80512 13.1905 7.80512 5.05999 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000364d2568>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BE"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003a39bda8>
;   Layer = "0"
;   Length (RO) = 27.1381
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 115
;   ObjectID32 (RO) = 115
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 112
;   OwnerID32 (RO) = 112
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003a39c0a0>
;   Visible = -1
 />
<DwgEntity
#<VLA-OBJECT IAcadLWPolyline 000000003a03d158>
; IAcadLWPolyline: AutoCAD Lightweight Polyline Interface
; Property values:
;   Application (RO) = #<VLA-OBJECT IAcadApplication 000000013fa12308>
;   Area (RO) = 299.943
;   Closed = -1
;   ConstantWidth = 0.0
;   Coordinate = ...Indexed contents not shown...
;   Coordinates = (10.5056 13.9399 39.1986 13.9399 39.1986 3.48634 ... )
;   Document (RO) = #<VLA-OBJECT IAcadDocument 00000000364d2568>
;   Elevation = 0.0
;   EntityTransparency = "ByLayer"
;   Handle (RO) = "1BD"
;   HasExtensionDictionary (RO) = 0
;   Hyperlinks (RO) = #<VLA-OBJECT IAcadHyperlinks 000000003a39c228>
;   Layer = "0"
;   Length (RO) = 78.293
;   Linetype = "ByLayer"
;   LinetypeGeneration = 0
;   LinetypeScale = 1.0
;   Lineweight = -1
;   Material = "ByLayer"
;   Normal = (0.0 0.0 1.0)
;   ObjectID (RO) = 116
;   ObjectID32 (RO) = 116
;   ObjectName (RO) = "AcDbPolyline"
;   OwnerID (RO) = 112
;   OwnerID32 (RO) = 112
;   PlotStyleName = "ByLayer"
;   Thickness = 0.0
;   TrueColor = #<VLA-OBJECT IAcadAcCmColor 000000003a39c520>
;   Visible = -1
